export default () => ({
  NODE_ENV: process.env.NODE_ENV || 'development',
  PORT: parseInt(process.env.PORT || '3001', 10),
  API_PREFIX: process.env.API_PREFIX || 'api',
  APP_URL: process.env.APP_URL || 'http://localhost:3000',
  API_URL: process.env.API_URL || 'http://localhost:3001',
  DEMO_MODE: process.env.DEMO_MODE !== 'false',
  REAL_MONEY_ENABLED: process.env.REAL_MONEY_ENABLED === 'true',
  DATABASE_URL: process.env.DATABASE_URL,
  DATABASE_SSL: process.env.DATABASE_SSL === 'true',
  REDIS_URL: process.env.REDIS_URL || 'redis://localhost:6379',
  JWT_SECRET: process.env.JWT_SECRET || 'dev-insecure-change-me',
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET || 'dev-insecure-refresh-change-me',
  JWT_ACCESS_EXPIRES: process.env.JWT_ACCESS_EXPIRES || '15m',
  JWT_REFRESH_EXPIRES: process.env.JWT_REFRESH_EXPIRES || '7d',
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
  COOKIE_DOMAIN: process.env.COOKIE_DOMAIN || 'localhost',
  COOKIE_SECURE: process.env.COOKIE_SECURE === 'true',
  RATE_LIMIT_TTL: parseInt(process.env.RATE_LIMIT_TTL || '60', 10),
  RATE_LIMIT_LIMIT: parseInt(process.env.RATE_LIMIT_LIMIT || '100', 10),
  SEED_DEMO_CREDITS: parseInt(process.env.SEED_DEMO_CREDITS || '10000', 10),
  SEED_ADMIN_EMAIL: process.env.SEED_ADMIN_EMAIL || 'admin@apexc casino.com',
  SEED_ADMIN_PASSWORD: process.env.SEED_ADMIN_PASSWORD || 'Admin123!',
  SEED_PLAYER_EMAIL: process.env.SEED_PLAYER_EMAIL || 'demo@apexc casino.com',
  SEED_PLAYER_PASSWORD: process.env.SEED_PLAYER_PASSWORD || 'Demo123!',
  ALLOWED_COUNTRIES: (process.env.ALLOWED_COUNTRIES || 'US,CA,GB,DE,NL,SE,NO,FI,DK,AU,NZ').split(','),
  RESTRICTED_COUNTRIES: (process.env.RESTRICTED_COUNTRIES || '').split(',').filter(Boolean),
});
