export const DEMO_CURRENCY = 'DEMO';
export const DEFAULT_DEMO_CREDITS = 10_000;

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  BET_LIMIT_EXCEEDED: 'BET_LIMIT_EXCEEDED',
  SELF_EXCLUDED: 'SELF_EXCLUDED',
  AGE_RESTRICTED: 'AGE_RESTRICTED',
  REAL_MONEY_DISABLED: 'REAL_MONEY_DISABLED',
  GAME_UNAVAILABLE: 'GAME_UNAVAILABLE',
  SESSION_INVALID: 'SESSION_INVALID',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
