export const DEMO_CURRENCY = 'DEMO';
export const DEFAULT_DEMO_CREDITS = 10_000;

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  SELF_EXCLUDED: 'SELF_EXCLUDED',
  REAL_MONEY_DISABLED: 'REAL_MONEY_DISABLED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
