export const DEMO_CURRENCY = 'DEMO';
export const DEFAULT_DEMO_CREDITS = 10_000;

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  BET_LIMIT_EXCEEDED: 'BET_LIMIT_EXCEEDED',
  LOSS_LIMIT_EXCEEDED: 'LOSS_LIMIT_EXCEEDED',
  SESSION_LIMIT_EXCEEDED: 'SESSION_LIMIT_EXCEEDED',
  SELF_EXCLUDED: 'SELF_EXCLUDED',
  AGE_RESTRICTED: 'AGE_RESTRICTED',
  GEO_RESTRICTED: 'GEO_RESTRICTED',
  REAL_MONEY_DISABLED: 'REAL_MONEY_DISABLED',
  KYC_REQUIRED: 'KYC_REQUIRED',
  GAME_UNAVAILABLE: 'GAME_UNAVAILABLE',
  SESSION_INVALID: 'SESSION_INVALID',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export const MIN_BET_DEMO = 0.1;
export const MAX_BET_DEMO = 500;
export const DEFAULT_CURRENCY = 'DEMO';
